#!/usr/bin/env ruby
# coding: utf-8
#
# GitHelp: ExpandHelpでGitを使いこなす
#
#  % githelp README 3 変化
#  [0] README.mdというファイルの3日前からの変化を表示する
#   git log --since="3 days ago" --oneline | tail -1 | ruby -lane 'puts $_.split(/ /).first' | xargs -J xxx git diff xxx README.md
#  %
#

# 変更されたファイルをすべてコミットする
# 変更されたファイルをリストする
# ファイルをリネームする
# 3回以上コミットされたファイルをリストする

progpath = $0
if File.symlink?(progpath)
  progpath = File.readlink(progpath)
end
progdir = "#{File.dirname(progpath)}"

require "#{progdir}/lib/githelp"

list = githelp(" #{args.join(' ')} ")
list.each_with_index { |entry,ind|
  puts "[#{ind}] #{entry[0]}"
  puts "   " + entry[1]
}

if list.length > 0 then
  print "実行するコマンドの番号を入力して下さい > "
  s = STDIN.readline
  if s =~ /[0-9]/ then
    i = s.to_i
    if i >= 0 && i < list.length then
      cmd = list[i][1]
      puts cmd
      system "PATH=$PATH:#{progdir}/bin; (#{cmd})"
    end
  end
end

