#!/usr/bin/env ruby
# coding: utf-8
#
# GitHelp: ExpandHelpでGitを使いこなす
#
#  % githelp README 3 変化
#  [0] README.mdというファイルの3日前からの変化を表示する
#   git log --since="3 days ago" --oneline | tail -1 | ruby -lane 'puts $_.split(/ /).first' | xargs -J xxx git diff xxx README.md
#  %
#

require 're_expand'
require './lib/files'
require './lib/args'
require './lib/params'

datadir = "#{File.dirname($0)}/data"

pat = " #{ARGV.join(' ')} "

entries = []
Dir.open(datadir).each { |file|
  next unless File.file?("#{datadir}/#{file}")
  next if file !~ /\.rb$/
  a = eval File.read("#{datadir}/#{file}")
  entries += a if a
}

g = ExpandRuby::Generator.new # re_expandのジェネレータ
entries.each { |entry|
  g.add entry[0], entry[1]
}

res = g.generate pat
res[0].each_with_index { |a,i| # ambig 0
  puts "[#{i}] #{a[0]}"
  puts a[1]
}

